In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1.anchored_artists import AnchoredSizeBar

# general libraries
import os  # make folders for file output
import h5py as h5
import json

from analysis import *
from general_utils import *
from scalebars import *

In [2]:
%matplotlib notebook
plt.rcParams.update({"figure.max_open_warning": 0})

In [3]:
# data_path = "/mnt/Data/NEURONoutput/sac_net/committee_runs/"
base_path = "/mnt/Data/NEURONoutput/sac_net/"
dir_labels = [225, 270, 315, 0, 45, 90, 135, 180]

## TODO:
- enable parallel runs with saving to h5 along the way, as done with the sac-sac models
- update the synapses to enable poisson quantal input, as in the sac-sac model
- fill out notebook with figures and interactive displays

In [4]:
model_path = os.path.join(base_path, "model_runs")
save_name = "test"
load_name = None

if load_name is not None:
    with h5.File(os.path.join(model_path, load_name + ".h5"), "r") as f:
        data = unpack_hdf(f)
else:
    from ei_balance_nogui import *
    os.makedirs(model_path, exist_ok=True)
    save_path = os.path.join(model_path, save_name) + ".h5"

    dsgc = Model(configs.sac_mode_config())
    rig = Rig(dsgc, model_path + "/")
    rig.synaptic_density()

    rig.sac_net_run(n_nets=3, n_trials=3, rho_steps=[0.0, 1.0])

    with h5.File(save_path, "r") as pckg:
        data = unpack_hdf(pckg)

	1 
Number of terminal dendrites: 177
# of synapses = 309
There are 0.0538 synapses per micron (for synaptic dendrites).
trial 0... 225 270 315 0 45 90 135 180 
trial 1... 225 270 315 0 45 90 135 180 
trial 2... 225 270 315 0 45 90 135 180 
spRho: 1.00	tmRho: 1.00
sacRho: 0.00	theta vars: E=60, I=60
DSis: [0.337 0.331 0.306]
thetas: [-36.2 -29.7 -24.2]
spikes: [[ 9 16 21 16 13  5  7  4]
 [ 8 12 20 15 11  9  2  6]
 [ 8 15 16 17 11 12  2  5]]
total_spikes: [25 43 57 48 35 26 11 15]
avg_DSi: 0.323
avg_theta: -30.32
DSis_sdev: 0.01
thetas_sdev: 4.9
num_GABA: 130

trial 0... 225 270 315 0 45 90 135 180 
trial 1... 225 270 315 0 45 90 135 180 
trial 2... 225 270 315 0 45 90 135 180 
spRho: 1.00	tmRho: 1.00
sacRho: 0.00	theta vars: E=60, I=60
DSis: [0.311 0.288 0.303]
thetas: [-9.7 -9.3 -4.1]
spikes: [[ 5 10 14 17 13  6  6  5]
 [ 7  9 15 15 12  9  5  4]
 [ 5 11 14 15 15 10  3  6]]
total_spikes: [17 30 43 47 40 25 14 15]
avg_DSi: 0.3
avg_theta: -7.65
DSis_sdev: 0.01
thetas_sdev: 2.55
num_GABA:

FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/mnt/Data/NEURONoutput/sac_net/model_runs/test.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)